/*
CLEAN UP CLASS REMOVING ALL OF THE GUI ELEMENTS


Single Events with graphics

TIMELINE GUI:
  MAKE A CURVE OR SINGLE EVENT
  INDICATE DURATION AND Y RANGE AND TIME LOCATION IN TIMELINE
  PRESS A BUTTON IT WILL SEND TO TIMELINE


MAKE THE BIZIER CURVE MAKER AS A SEPARATE SKETCH or using controlp4
BE ABLE TO SET THE ON, OFF AND CURVE Y MESSAGES
BE ABLE TO HAVE TRIGGER MESSAGES AT SOME POINT IN CURVE, HAVE SOME GRAPHIC TO REPRESENT
  HAVE THE SKETCH BE ABLE TO STORE PRESET CURVES AND THEN CHANGE WHERE IT SHOWS UP ON TIMELINES AND ITS DURATION AND YAXIS
TIME MARKERS IN TIMELINES AND WAY OF SETTING UP THE SCORE DYNAMICALLY
*/
